[options]
http_interface = 0.0.0.0

admin_passwd = JajNav5@2119
db_host = postgres_dev
db_port = 5432
db_user = odoo_user
db_password = jajnav5@

# Important: Map the container path defined in Dockerfile/Compose
addons_path = /mnt/addons,/mnt/tutorials,/usr/lib/python3/dist-packages/odoo/addons